const { GoogleGenerativeAI } = require("@google/generative-ai");
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

class GeminiService {
  constructor(apiKey) {
    this.genAI = new GoogleGenerativeAI(apiKey);
    this.model = this.genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
  }

  async chat(message, history = [], workspaceId) {
    const context = await this.getContext(workspaceId);
    
    // Self-Reflection Step: AI critiques its own advice
    const reflectionPrompt = `
      Context: ${JSON.stringify(context)}.
      User Input: ${message}.
      Draft Advice: [To be generated by primary model].
      Critique the draft advice based on COD profitability rules (ROAS > 2x, CPA < target).
    `;

    const result = await this.model.generateContent(`Context: ${JSON.stringify(context)}. User: ${message}. Provide advice AND critically evaluate its impact on profitability.`);
    const responseText = result.response.text();
    
    // Log for telemetry & learning
    await prisma.actionLog.create({
      data: {
        workspaceId,
        actionType: 'CHAT_WITH_REFLECTION',
        input: { message },
        output: { response: responseText },
        tokensUsed: 300 
      }
    });

    return responseText;
  }
}

module.exports = GeminiService;
